### ISSUE TITLE
Setting to force x64 (or x86) versions of a package to be installed.

### ISSUE THREAD

**Issue by LinkofHyrule89** [chocolatey/ChocolateyGUI#262] opened 2015-05-26 08:31 UTC
I would like a setting in ChocolateyGUI to force packages to install the x64 version of a package if avaliable. You might even consider having a context menu when you right click it to install x64 or x86 but the setting will install which ever one you want as default.

**Comment by gep13** [comment] 2015-05-26 19:22
Hmm, this is an interesting one.

I will have to mull this one over.  The default installation would be to install the version that matches the architecture of the current machine.  But I could see an option to force the installation of the x86 version, on a x64 machine.  You obviously wouldn't want to go the other way.

**Comment by LinkofHyrule89** [comment] 2015-05-26 20:00
I wasn't sure if it installed x64 by default or how it worked but
that's good know know thanks.

**Comment by gep13** [comment] 2015-05-27 06:13
Yip, based on the architecture of the machine you are installing on, Chocolatey will attempt to install that version of the application.  For some packages, there is only a 32bit version of the application, so it obviously can't install the 64bit version, so it will fall back to that.  However, when there is both a 32 bit and a 64 bit download URL, and you are on a 64 bit system, ChocolateyGUI should provide the ability to force the install of the 32bit version.

Thanks for submitting this issue.

**Comment by Vaquero84** [comment] 2015-08-15 02:21
This would be great. The bitness of certain development tools you choose is determined not by your own system, but by who you are developing for. So I could be on a x64 machine but need a 32bit version of a sdk for developing 32bit apps.

**Comment by RichiCoder1** [comment] 2015-09-25 18:28
Related to #267. Would require us to expose a dialog or setting to allow this. I think choco only supports force x86.

**Comment by jorrit** [comment] 2018-11-22 08:51
Perhaps related, but Chocolatey GUI installs the 64-bit version of Notepad++ when updating, even when I currently have the 32-bit version on my machine.

**Comment by gep13** [comment] 2019-04-23 08:22
This is really a duplicate of the intended functionality in this issue:

https://github.com/chocolatey/ChocolateyGUI/issues/545

As such, I am going to close this one out, and use that issue as the main one to track.

**Closed by gep13** 2019-04-23 08:22 UTC
Labels: Duplicate
