### ISSUE TITLE
Scroll via mouse wheel seems backwards.

### ISSUE THREAD

**Issue by cbussa** [chocolatey/ChocolateyGUI#567] opened 2018-03-01 07:01 UTC
(I've looked and don't see this listed anywhere.  I also don't believe this is an enhancement.  If so, I'll resubmit correctly.)

C-GUI v0.16.0 on Windows 10 current, new install, running as Admin under an elevated prompt.

Launching and selecting the chocolately repository, everything fetches and works correctly.  Once completed, I can scroll the item list with the cursor keys (after first selecting a random item) or by the mouse (by just moving it over the window and scrolling the mouse wheel, focus or no focus.)

But every other app I have works like:  scrolling the mouse towards you scrolls the window downwards, and away scrolls upwards. (I. e. moving the top of the mouse wheel towards you produces a "screen scrolls down within the window / cursor down" effect, while moving it "away" from you scrolls the screen upwards / cursor up.)

It'd be nice if a downwards mouse scroll would move the screen downwards, and vise versa, matching the action of all (most?) other apps.  (A decade ago Mansfield K-Edit had this exact problem -- the solution was that the mouse scroll-by-lines movement function was set to scroll +1 when it should have been -1. (Or vice versa, it's been a decade, and I wasn't the programmer.)

It'd _also_ be nice if C-GUI would support scrolling by an entire page if set in windows (action is PgDn instead of a single-line cursor down), but that's another ticket for another day.

![image](https://user-images.githubusercontent.com/3461529/36830853-fbcb9af2-1cea-11e8-80fa-4c91e8b0b562.png)

**Comment by corbob** [comment] 2022-09-30 18:00
Thanks for the report @cbussa! Would you be able to verify if this is still happening for you? I'm unable to reproduce this in either Chocolatey GUI 0.16.0, or in Chocolatey GUI 1.1.0.

Just so we're on the same page: when I say reproduce, what I am doing is mousing over Chocolatey GUI and scrolling my mouse wheel, then I am mousing over a Microsoft Edge window and scrolling my mouse wheel. In both instances, the scroll behaves the same for both windows.

**Comment by pauby** [comment] 2023-06-28 12:01
There has been no update on this for some time. I'm going to go ahead and close this, but we can reopen it if necessary.

**Closed by pauby** 2023-06-28 12:01 UTC
Labels: Can't Reproduce, 0 - _Triage
