### ISSUE TITLE
Files of Programs Persists after Chocolatey GUI Uninstallation

### ISSUE THREAD

**Issue by Riajyuu** [chocolatey/ChocolateyGUI#571] opened 2018-03-04 02:29 UTC
environ:
Chocolatey 0.10.8
Core Ext 1.3.3
GUI 0.15.0
Windows 10 Pro latest release

STR:
Install any program, VLC for example. All files of VLC is installed in C:\Program Files. And then uninstall it with GUI.

Actual Results:
VLC is not display in the GUI but all files of VLC remain untouched, including the shortcut.

Expected Results:
All files of VLC should have been removed.

**Comment by gep13** [comment] 2019-04-23 08:12
@Riajyuu thank you for raising an issue about this.

I have just tested the steps that you provided, and I have been unable to reproduce the problem.

As such, I am going to close this issue.  If you feel that this is still a problem, please feel free to comment again.

**Closed by gep13** 2019-04-23 08:12 UTC
Labels: Can't Reproduce
