### ISSUE TITLE
Chocolatey GUI throws repeated HttpRetryHandler warnings while attempting to update Chocolatey package list

### ISSUE THREAD

**Issue by thedoctorjtd** [chocolatey/ChocolateyGUI#1009] opened 2023-06-06 16:13 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

When opening `ChocolateyGUI` and selecting the `chocolatey` tab, loading seems to take an extremely long time to complete (up to a minute). Expanding console output yields this repeated output:

```
Fetching packages...
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'cheatengine') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'cheatengine') and IsLatestVersion&semVerLevel=2.0.0 76ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   OK https://community.chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 200ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey') and IsLatestVersion&semVerLevel=2.0.0 24ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=30&$top=20&semVerLevel=2.0.0
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   OK https://community.chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=30&$top=20&semVerLevel=2.0.0 344ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Search()/$count?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Search()/$count?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''&targetFramework=''&includePrerelease=false&semVerLevel=2.0.0 538ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-compatibility.extension') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-compatibility.extension') and IsLatestVersion&semVerLevel=2.0.0 25ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-core.extension') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-core.extension') and IsLatestVersion&semVerLevel=2.0.0 23ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq '7zip') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq '7zip') and IsLatestVersion&semVerLevel=2.0.0 22ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-dotnetfx.extension') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-dotnetfx.extension') and IsLatestVersion&semVerLevel=2.0.0 22ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq '7zip.install') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq '7zip.install') and IsLatestVersion&semVerLevel=2.0.0 35ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolateygui') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolateygui') and IsLatestVersion&semVerLevel=2.0.0 23ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'advanced-ip-scanner') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'advanced-ip-scanner') and IsLatestVersion&semVerLevel=2.0.0 20ms
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-visualstudio.extension') and IsLatestVersion&semVerLevel=2.0.0
[NuGet]   OK https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'chocolatey-visualstudio.extension') and IsLatestVersion&semVerLevel=2.0.0 24ms
[NuGet]   GET https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id) eq 'bind-toolsonly') and IsLatestVersion&semVerLevel=2.0.0
[NuGet] Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
```

This continues for quite some time before finally completing and successfully showing the repository of packages.

### What is Expected?

Prior to the 2.0 update the load of packages would take only a few seconds. Now it is upwards of a minute post 2.0 update. There is at least one other person experiencing this issue: http://disq.us/p/2uk1fmf

I am unsure if the HttpRetryHandler warning was present before V2.0, however the load time is certainly increased drastically. Again, this isn't a slight increase, this was a long enough increase that after seeing the console I assumed there was a bug and that it would not complete. From 5, maybe 10 seconds to now over a minute (estimated). Notably the download does finish, it just takes an incredibly long time. 

### How Did You Get This To Happen?

Open ChocolateyGUI
*Automatic UAC Elevation* -> Approve
ChocolateyGUI loads into the `This PC` tab
Select `chocolatey` tab

This is where the long load begins. The output provided above was copied from the built in console output.

### System Details

* Operating System: 10.0.19045.0
* Windows PowerShell version: 7.3.4
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version:
```
PS C:\Users\xxx> choco list chocolatey.extension --local --exact
Chocolatey v2.0.0
Invalid argument --local. This argument has been removed from the list command and cannot be used.
PS C:\Users\xxx> choco list chocolatey.extension --exact
Chocolatey v2.0.0
0 packages installed.
```
* Chocolatey License type: Community/Free
* Terminal/Emulator: Microsoft Terminal running PS 7 (this is what generated my outputs here, however the issue I experienced was not related to the terminal at all)

### Installed Packages

```bash
PS C:\Users\xxx> choco list -lo
Chocolatey v2.0.0
Invalid argument -lo. This argument has been removed from the list command and cannot be used.
PS C:\Users\xxx> choco list
Chocolatey v2.0.0
7zip 22.1.0
7zip.install 22.1.0
advanced-ip-scanner 2.5.4594.1
bind-toolsonly 9.16.28
cheatengine 7.5.0
chocolatey 2.0.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
chocolateygui 2.0.0
chocolatey-visualstudio.extension 1.11.0
chocolatey-windowsupdate.extension 1.0.5
chrome-remote-desktop-chrome 63.0.3239.17
chrome-remote-desktop-host 114.0.5735.35
dbeaver 23.1.0
docker-desktop 4.19.0
dotnet-7.0-desktopruntime 7.0.5
dotnet-desktopruntime 7.0.5
dotnetfx 4.8.0.20220524
filezilla 3.64.0
Firefox 113.0.2
git 2.41.0
git.install 2.41.0
GoogleChrome 114.0.5735.110
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
KB3063858 1.0.0
KB3118401 1.0.5
kitty 0.76.1.12
microsoft-edge 114.0.1823.37
microsoft-windows-terminal 1.16.10261
nirlauncher 1.30.2
notepadplusplus 8.5.3
notepadplusplus.install 8.5.3
powershell-core 7.3.4
powertoys 0.70.1
putty 0.78.0
putty.install 0.78.0
putty.portable 0.78.0
python 3.11.3
python3 3.11.3
python310 3.10.11
python311 3.11.3
python38 3.8.10
ripcord 0.4.29
sandboxie-plus.install 1.9.6
shutup10 1.9.1435
spotify 1.2.12.902
superputty 1.5.0
superputty.install 1.5.0
sysinternals 2023.5.24
teracopy 3.9.7
treesizefree 4.6.3
vcredist140 14.36.32532
vcredist2015 14.0.24215.20170201
visualstudio2019buildtools 16.11.26
visualstudio2019-workload-vctools 1.0.1
visualstudio-installer 2.0.3
vlc 3.0.18
vlc.install 3.0.18
vscode 1.78.2
vscode.install 1.78.2
wireshark 4.0.6
```

### Output Log

```bash
https://gist.github.com/thedoctorjtd/bb09b30df14018324ac67696cafa64a2
```

**Comment by TheCakeIsNaOH** [comment] 2023-06-06 22:37
@thedoctorjtd This appears to be the same as https://github.com/chocolatey/choco/issues/3183, so it hopefully should be fixed in ChocolateyGUI once Chocolatey CLI v2.1.0 is released and ChocolateyGUI is updated to use it.

**Comment by gep13** [comment] 2023-06-09 07:02
I agree with @TheCakeIsNaOH here.  The logging output that you are seeing comes from Chocolatey CLI, not Chocolatey GUI, so the necessary change is in the upstream Chocolatey CLI, not here.  This issue has been corrected there via https://github.com/chocolatey/choco/issues/3183.

There are new alpha packages available for both Chocolatey CLI and GUI.  If you are in a position to do so, installing those alpha versions, and verifying that the problem is resolved would be very helpful.

For now, I am going to close this issue, but please feel free to respond back if the problem is not actually resolved.

**Closed as completed by gep13** 2023-06-09 07:02 UTC

**Comment by superdale007** [comment] 2023-06-19 16:24
experiencing the same as of today.

**Comment by gep13** [comment] 2023-06-19 16:51
@superdale007 can you confirm what version of Chocolatey CLI and GUI you are using? The fix for this is only in the latest alpha versions, not the stable ones.

**Comment by gep13** [comment] 2023-06-19 18:20
> @superdale007 said...
I'm running stable...both choco & GUI = v2.0.0.0

As noted above, this issue was associated with another one in the Chocolatey CLI repository:

https://github.com/chocolatey/choco/issues/3183

And you will see that that issue is assigned to the 2.1.0 milestone, which hasn't been shipped yet.  There are alpha packages available of both Chocolatey CLI and GUI, where the issue has been addressed, which you can try out if you would like.  Or you can wait for the release of the next stable version of the Chocolatye products.

**Comment by superdale007** [comment] 2023-06-19 18:28
Thanks gep13 for explaining #NoobieOnLine

**Comment by gep13** [comment] 2023-06-19 18:53
> @superdale007 said...
Thanks gep13 for explaining #NoobieOnLine

Ha ha! You are very welcome! Feel free to reach out if you have any other questions. You can jump into https://ch0.co/community which is a link to our Discord Server.
