### ISSUE TITLE
ChocolateyGUI stuck on "Retrieving installed packages"

### ISSUE THREAD

**Issue by sanchezelton** [chocolatey/ChocolateyGUI#302] opened 2016-02-29 17:16 UTC
ChocolateyGUI stuck on "Retrieving installed packages" on startup. Does ChocolateyGUI still support only choco 0.9.8.x?

According to > choco list ChocolateyGUI and > choco --version
* My version of choco: 0.9.9.11
* My version of chocoGUI: 0.13.2 
Running Windows 7 Enterprise SP1.

**Comment by gep13** [comment] 2016-02-29 20:01
@sanchezelton thanks for getting in touch.  This is a duplicate of https://github.com/chocolatey/ChocolateyGUI/issues/266 which has a workaround mentioned in the issue.

I am going to close this for now, but follow the other issue for any progress on the underlying problem.

**Comment by gep13** [comment] 2016-02-29 20:02
@sanchezelton to answer your question though, no, ChocolateyGUI should support both the PowerShell and C# version of Chocolatey.

**Closed by gep13** 2016-02-29 20:02 UTC
