### ISSUE TITLE
Add feature toggle for HideThisPCSource

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#859] opened 2021-06-02 18:22 UTC
The work here would be to add a feature toggle to control whether or not the This PC source is shown within the Chocolatey GUI interface.

The implementation of this feature would then be handled in the Chocolatey GUI Licensed Extension.

**Comment by gep13** [comment] 2021-06-02 18:24
The follow up work to actually do something when this feature is enabled would be carried out here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/228

**Comment by ryanrichter94** [comment] 2022-06-24 15:45
Duplicate of #884

**Closed** 2022-06-24 15:45 UTC
