### ISSUE TITLE
Creates two directories under ProgramData

### ISSUE THREAD

**Issue by HunterZ** [chocolatey/ChocolateyGUI#534] opened 2017-11-18 16:24 UTC
I just started using ChocolateyGUI and noticed that it created to folders under C:\ProgramData: `Chocolatey GUI` and `ChocolateyGUI`. I'm pretty sure the first one is some kind of typo, as it is empty, while the second has a log file.

I'd include a version number, but there isn't one in the about page, title bar, log file, etc. Oh - I guess it's in the package list: 0.15.0.

**Comment by gep13** [comment] 2017-11-18 17:26
@HunterZ thanks for reaching out, you bring up a few points here, but I think I can explain most of them.

In the 0.15.0 release, we reconciled on using `Chocolatey GUI` as the application, rather than `ChocolateyGUI`.  This was changed everywhere, including the installation folder.  The issue that was tracking this is [here](https://github.com/chocolatey/ChocolateyGUI/issues/402).  The fact that you have both folders suggests that you have had an earlier version of Chocolatey GUI installed prior to installing the latest.  The programdata folder is used to collect log files for the application when it is running, and these aren't removed as part of uninstalling the older version of the application.

Regarding the missing version number in the About section.  This was a bug that was introduced in the 0.16.0 release.  This is being tracked [here](https://github.com/chocolatey/ChocolateyGUI/issues/499).

Please let me know if this explains the issues that you bring up.

**Comment by HunterZ** [comment] 2017-11-18 18:01
No, I did not have this installed before on either of the two machines on which I installed it today, and both folders have today's date. I'm pretty sure you missed something somewhere.

**Comment by HunterZ** [comment] 2017-11-18 18:06
The issue may be in `Bootstrapper.cs`, where it sets `internal const string ApplicationName = "ChocolateyGUI";` and then uses this in `Configure()` when forming `LocalAppDataPath` and `AppDataPath`.

**Comment by gep13** [comment] 2017-11-18 18:15
Hmm, interesting....

I was convinced that I had changed all references to ChocolateyGUI, but I will definitely look into the area of the code that you mention.

Thanks for pointing this out.

**Comment by gep13** [comment] 2017-11-19 20:50
@HunterZ I have just investigated this, and I can confirm that the issue is as you described.  The MSI installer was generated the `Chocolatey GUI` folder, and the bootstrapper was creating the `ChocolateyGUI` folder.  This will be fixed in the next release.

**Closed** 2017-11-19 20:53 UTC
Labels: Bug
