### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by aminya** [chocolatey/ChocolateyGUI#777] opened 2020-05-28 04:15 UTC
I really love chocolateyGUI, however, when compared to the Chocolatey website itself or other stores like Microsoft Store, it is considered much slower. For example, even fetching the package names on each page takes a long time.

What are the plans for improving the performance?

I understand that checking for the outdated packages might take a long time, but I don't understand why this checking should happen during the startup in a blocking manner. Usually, the programs do their best to not block the UI by making everything run asynchronously and on other threads. 

Here is more info in case it helps:

```ps1
❯ Measure-Command { choco outdated -r }

Seconds           : 18
Milliseconds      : 715
```

```ps1
❯ choco list -l
131 packages installed.
```

**Comment by pauby** [comment] 2024-04-16 12:47
Thsi is a duplicate of #789.

**Closed** 2024-04-16 12:48 UTC
