### ISSUE TITLE
Duplicated entries

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#370] opened 2016-12-22 11:43 UTC
I somehow managed to have the entries in the "This PC" list to be duplicated:

![unbenannt](https://cloud.githubusercontent.com/assets/2190718/21424597/2f48e68e-c844-11e6-8888-40a74fd59a30.png)

Not sure how to reproduce though (I did reinstall one app, clicked once on the refresh button, switched between normal and updated view)

**Comment by RichiCoder1** [comment] 2016-12-22 17:02
You're no the first person to see this, but I've never been able to reproduce. If you do manage, please let me know.

**Comment by gep13** [comment] 2017-10-02 20:31
@pascalberger since the refactoring, I haven't been able to reproduce this either.

Going to close this just now, feel free to comment back again if you can reproduce the issue.

**Closed by gep13** 2017-10-02 20:31 UTC
Labels: Bug
