### ISSUE TITLE
Add tooling for localization (automatic 'missing string' detection)

### ISSUE THREAD

**Issue by mwallner** [chocolatey/ChocolateyGUI#416] opened 2017-02-26 08:32 UTC
it'd be great to have some tooling to determine which strings need to be 
* added
* removed
* changed

(among the different Resources.*.resx)

**Comment by mwallner** [comment] 2017-02-26 08:33
CC @gep13 @RichiCoder1

**Comment by mwallner** [comment] 2017-02-26 18:32
I'll give https://github.com/HakanL/resxtranslator a shot
* if it works as I expect, I'll add it to the howto

**Comment by gep13** [comment] 2017-02-26 18:47
@mwallner that looks really useful!

**Comment by mwallner** [comment] 2017-02-26 18:48
![image](https://cloud.githubusercontent.com/assets/5354972/23342526/8e4bea2c-fc5c-11e6-8ffc-1152533f7d22.png)
 it even runs on linux ❤️

**Comment by mwallner** [comment] 2017-02-26 18:59
aaand the encoding exploded + all EOL and EOF are dead to 🤣 - will try tomorrow on Windows OS!

**Comment by gep13** [comment] 2017-02-26 19:00
Ah, perhaps we need some additional entries in the .gitattributes file.

**Comment by RichiCoder1** [comment] 2017-02-26 20:44
Haha, oh my. Do let me know how it goes though, I'd love to see some tooling to make this easier for contributors

**Comment by mwallner** [comment] 2017-03-02 11:38
Works great on Windows! :-)
![image](https://cloud.githubusercontent.com/assets/5354972/23505697/0c53b6e4-ff45-11e6-9378-3af3fd72d921.png)

**Comment by mwallner** [comment] 2017-03-02 11:38
(keeps encoding and works just as expceted!)

**Comment by AdmiringWorm** [comment] 2017-03-13 16:33
Another option could be to setup a project on [transifex](https://www.transifex.com/) (free for OSS).
I've used it a few times in the past, and IMO is great.
It could be set up to monitor a remote url for changes, synchronizing it whenever it is changed (not quite sure how often it is checked though).

With that it could also be integrated into the build script to download all translated strings (any language) during build by using their cli client.

**Comment by AdmiringWorm** [comment] 2017-03-15 20:29
> That'd be great! - any experience working with this tool considering .resx ?

It's been quite some time since I last setup a project on transifex, so the procedure may have changed a little.
.resx files is supported by transifex without doing any modifications though, so that should be easy enough.

> how about adding new languages?

Adding new languages can be added by the members that have the required privileges, those who do not have them can request/suggest a new language to be added (New translators would also need to request to be added to the language).

> do you have resources to setup a demo?

I don't right now, but I'll try setting up a simple hello world demo hopefully soon.

**Comment by RichiCoder1** [comment] 2017-03-16 04:59
@AdmiringWorm Let me know if you need any help on that. Rather curious myself. Heard good things about Transifex in the past.

**Comment by magol** [comment] 2017-03-16 07:03
I have used transifex to translate multiple projects, and I like the interface. 
I vote that we use transifex.

**Comment by AdmiringWorm** [comment] 2017-03-16 09:39
I've set up a basic hello world demo here: https://github.com/AdmiringWorm/Hello-Transifex

I still have left to provide some documentation on how the transifex client is initialized, and how the project is set up on transifex.

**Comment by gep13** [comment] 2017-03-16 09:44
@AdmiringWorm is this something that would be done as part of the CI build, or would this be done manually and added as part of a PR to the repo?

**Comment by AdmiringWorm** [comment] 2017-03-16 09:55
@gep13 it can be done both manually, and through a CI build (requires a small hack for that though).
The demo project I linked to is set up to ignore the Resource.<lang>.resx files (only including the default Resource file) and download the translations when it is run on appveyor.

**Comment by gep13** [comment] 2017-03-16 09:56
@AdmiringWorm cool, will take a look when I have a minute, sounds very interesting!

**Comment by AdmiringWorm** [comment] 2017-03-16 10:29
Some basic documentation have also been provided now on [the wiki](https://github.com/AdmiringWorm/Hello-Transifex/wiki) for how to set up the project on transifex, and configure the respository using the transifex client.

**Comment by AdmiringWorm** [comment] 2017-03-22 21:31
hmm, I just recently came across [lingohub](https://lingohub.com/).
I think this looks pretty good (and is also free for FOSS), and looks like it can be easier integrated with github (supports automatic pull from repo, (automatic?) push either directly or as a PR).
Still testing it out, but I'll update when I've messed around with it some more.

**Comment by gep13** [comment] 2017-03-25 15:33
>@AdmiringWorm said...
It also has the downside that it can be integrated into the build process to download translation files.

`can` or `can't`

**Comment by AdmiringWorm** [comment] 2017-03-25 19:16
> @gep13 said...
> can or can't

Ops, I meant can't

**Comment by gep13** [comment] 2017-10-23 20:11
@mwallner @AdmiringWorm @RichiCoder1 @magol I have started the process of setting up Transifex.  I "think" you should be able to see this here:

https://www.transifex.com/chocolatey/chocolatey-gui/dashboard/

Can you let me know if you all can see this?  If you could let me know your email addresses for Transifex (assuming you have one) I can get you added to the project.

**Comment by mwallner** [comment] 2017-10-23 20:19
Just put in a join request :-)

**Comment by gep13** [comment] 2017-10-23 20:35
@mwallner sweet! You should have access now :-D

**Comment by gep13** [comment] 2017-10-24 06:24
@magol that is great, I have accepted the request!  Thank you for yours and @mwallner continued help with this, it is a great addition to Chocolatey GUI.

**Comment by AdmiringWorm** [comment] 2017-10-24 14:34
I can confirm that I have access to the transifex project.

**Comment by mwallner** [comment] 2017-10-25 19:43
thanks @gep13 for setting up the account at https://www.transifex.com/chocolatey/chocolatey-gui/dashboard/ :-)
I'd suggest if you've verified the system works (maybe once Didier is done with the french translation?) you close this issue.

**Comment by AdmiringWorm** [comment] 2017-10-25 19:54
@gep13 @mwallner 
btw, I recommend that when transifex have been fully integrated with the build process, the best thing would be to only accept translations through transifex and not the through github itself.
Otherwise, you may end up with a headache of manually updating every string on transifex afterwards (since they may differ, maybe some work had already been done on transifex already).

As well as only storing the source resource itself in the repo, and not the translations.

**Comment by gep13** [comment] 2017-10-26 21:11
@AdmiringWorm totally agree.  I have implemented the required changes to make this possible going forward.

**Comment by gep13** [comment] 2017-11-01 21:31
Using the amazing work from @AdmiringWorm I "think" I have just completed the first build using the translated artifacts from Transifex 😄 

Version 0.16.0-unstable0072 has just been pushed to MyGet.

@pascalberger @mwallner @punker76 could I get you to take that version for a spin?  If this package successfully localizes to your environments, then I think we can go ahead and close this issue out, and continue using the Transifex service for additional translations.

Please let me know if you have any questions.

**Comment by punker76** [comment] 2017-11-01 23:14
@gep13 LGTM. Except the features group for Chocolatey, maybe this keys are currently missing?

![2017-11-02_00h10_49](https://user-images.githubusercontent.com/658431/32302404-d33f385e-bf62-11e7-8e60-08c722d8c803.png)
![2017-11-02_00h11_25](https://user-images.githubusercontent.com/658431/32302406-d35e2246-bf62-11e7-8acc-082dec4c2bb3.png)
![2017-11-02_00h11_31](https://user-images.githubusercontent.com/658431/32302407-d376d0f2-bf62-11e7-835c-34753c1baa9f.png)
![2017-11-02_00h11_46](https://user-images.githubusercontent.com/658431/32302408-d39112f0-bf62-11e7-9165-72510e255833.png)
![2017-11-02_00h12_32](https://user-images.githubusercontent.com/658431/32302409-d3acc8ba-bf62-11e7-8bdf-0ebd9a62dbbe.png)
![2017-11-02_00h12_36](https://user-images.githubusercontent.com/658431/32302410-d3c554e8-bf62-11e7-8880-a5ca78fe71cc.png)
![2017-11-02_00h12_39](https://user-images.githubusercontent.com/658431/32302411-d3e91bd0-bf62-11e7-8b63-478d39b10b03.png)

**Comment by punker76** [comment] 2017-11-01 23:20
@gep13 

![2017-11-02_00h12_32](https://user-images.githubusercontent.com/658431/32302554-9862ec48-bf63-11e7-9601-2c44b91659e9.png)
![2017-11-02_00h12_36](https://user-images.githubusercontent.com/658431/32302555-987b0de6-bf63-11e7-84dc-ac7c5cf7c6a6.png)

**Comment by AdmiringWorm** [comment] 2017-11-01 23:22
@punker76 I don't think the configurations from choco have been made translatable, probably because they are dynamically generated (just a guess).

The untranslated Source seems to be a mistake though.

**Comment by punker76** [comment] 2017-11-01 23:27
@AdmiringWorm The `Source` should be easy to fix.

https://github.com/chocolatey/ChocolateyGUI/blob/6b9ef923b94f53d3c5efdc1305bd2e6a29e2db90/Source/ChocolateyGui/Views/SettingsView.xaml#L136

**Comment by RichiCoder1** [comment] 2017-11-02 02:01
@AdmiringWorm Is correct. I believe we already raised this issue with @ferventcoder

**Comment by mwallner** [comment] 2017-11-02 06:40
LGTM, (looking great!), love the fact that we can now just point people to transifex :-)

**Comment by gep13** [comment] 2017-11-02 07:00
Ok, I am going to go ahead and close out this issue, as the main focus of this issue has been tackled, and we can raise other issues about the missing translations.

**Closed by gep13** 2017-11-02 07:00 UTC
Labels: Documentation

**Comment by gep13** [comment] 2017-11-02 08:14
@punker76 according to Transifex, the current English to German translation for `Features` is simply `Features`:

![image](https://user-images.githubusercontent.com/1271146/32315860-d61875ac-bfa5-11e7-9bbd-f137b8cbfc40.png)

If this isn't the case, or you can suggest something else, then we can get this changed.

**Comment by punker76** [comment] 2017-11-02 08:34
@gep13 @mwallner I added my suggestions

**Comment by gep13** [comment] 2017-11-02 08:50
@mwallner @pascalberger @x-jokay you guys are marked as translators/reviewers for the German Language.  It would be good to know if you guys get emailed/notified about this suggestion.  i.e. would be good to know what the workflow is around suggestions, and how they can get accepted.  Thanks!

**Comment by mwallner** [comment] 2017-11-02 09:41
hm, this is odd - I didn't receive any notification, neither per mail nor in the transifex UI.. also it's pretty hard to spot the 'overall' suggestions - thge only way I see currently is checking each string indivdually...
![image](https://user-images.githubusercontent.com/5354972/32319280-56764a1c-bfba-11e7-8092-7187926ca172.png)

**Comment by pascalberger** [comment] 2017-11-02 10:04
@gep13 No mail notification here either

**Comment by gep13** [comment] 2017-11-02 10:37
@mwallner @pascalberger seems like you might have to "watch" a language, in order to get these notifications, but I can't find how to add a watch onto a language 😢

**Comment by gep13** [comment] 2017-11-02 10:44
Okay, I have found how to "watch" a project, but not how to "watch" a language:

![image](https://user-images.githubusercontent.com/1271146/32321929-a65eef48-bfba-11e7-8d28-6f366bed2fd9.png)

Can someone add a suggestion to the German language?  I want to see if I get any additional notifications through now.

**Comment by punker76** [comment] 2017-11-02 10:47
@gep13 done

**Comment by gep13** [comment] 2017-11-02 11:21
@punker76 yeah, that hasn't helped :sad:

**Comment by ferventcoder** [comment] 2017-11-02 23:08
@gep13 can you make me an admin in the CHocolatey team? I joined just now... but I can't request. It's based on my ferventcoder username.

**Comment by ferventcoder** [comment] 2017-11-02 23:55
@punker76 https://github.com/chocolatey/choco/issues/1441

**Comment by gep13** [comment] 2017-11-03 07:17
@ferventcoder looks like you are all sorted, I think @AdmiringWorm must have hooked you up 😄
