### ISSUE TITLE
Shows all packages although "Show Only Packages with Updates" is ticked after "update all"

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/ChocolateyGUI#288] opened 2015-10-11 18:27 UTC
Reproduce:
Tick `Show Only Packages with Updates`
Klick `update all`
ChocolateyGui updates
After update ChocolateyGui shows all packages installed on this PC but `Show Only Packages with Updates` is still ticked

**Comment by RichiCoder1** [comment] 2015-10-12 16:20
Huh. Hmmm.

**Comment by Kreozot** [comment] 2015-11-25 10:01
For me this bug reproduces not only when doing "update all" but also when I'm updating any package.

**Comment by rob100** [comment] 2015-12-23 12:39
I looked at the issue and opened a pull request for this problem (GH-298).
This will improve the GUI behavior with two things:
1) Doing a "refresh packages" after "update all" to show the correct package information (e.g. version)
2) Unchecking the "Show Only Packages with Updates"

**Comment by urig** [comment] 2016-05-15 09:43
@rob100 Are you sure Unchecking the "Show Only Packages with Updates" checkbox is the best behavior here? IMHO the resolution to the inconsistency reported in the issue is to make the view match the user's selection (to check the checkbox) and not the other way around :)

**Comment by rob100** [comment] 2016-05-22 09:40
@urig I think both behaviors would be okay and much better than the current situation. But I agree, your solution seems to be a little bit more what the users expects.

**Comment by adamkruszewski** [comment] 2016-05-24 14:20
I have opened a pull request  #308  and I hope I have found all possibilites there where the filter should be applied after performing the operation.

**Comment by adamkruszewski** [comment] 2016-05-24 15:19
I haven't noticed the empty line I have removed, so I have amended my last commit to restore it. Bad habbit, sorry about that.

**Comment by RichiCoder1** [comment] 2016-12-18 12:18
Resolved in latest develop.

**Closed by RichiCoder1** 2016-12-18 12:18 UTC
Labels: Bug
