### ISSUE TITLE
Creates two folders - "ChocolateyGUI" AND "Chocolatey GUI"

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#546] opened 2017-11-30 22:27 UTC
In ProgramData I'm seeing a `ChocolateyGUI` and a `Chocolatey GUI` folder (note the space). I think the one with the space is created, but it's never used. I see the same in Program Files. It appears we have a lingering thing where one uses the name of the application and the other uses a non-spaced name.

**Comment by gep13** [comment] 2017-12-01 07:42
@ferventcoder this is a duplicate of this: https://github.com/chocolatey/ChocolateyGUI/issues/534

Which has already been addressed, and should go out in the next release.

**Closed by gep13** 2017-12-01 07:42 UTC
Labels: Duplicate

**Comment by ferventcoder** [comment] 2017-12-01 16:08
Ah thanks! I didn't see that one.
