### ISSUE TITLE
Choose what version of packages you want to install in the GUI

### ISSUE THREAD

**Issue by nutterthanos** [chocolatey/ChocolateyGUI#722] opened 2019-12-30 08:55 UTC
Maybe implement a gui box to choose what version of package you want just like how Hot Chocolatey already does it.
https://imgur.com/a/raFQw7f

**Comment by nutterthanos** [comment] 2020-08-31 05:21
why is this not getting replies?

**Comment by gep13** [comment] 2021-04-09 19:24
@nutterthanos apologies for not replying sooner about this, I didn't see the notifications about this issue.  This suggestion is really a duplicate of what was suggest here: https://github.com/chocolatey/ChocolateyGUI/issues/545.  There is an open PR for providing this functionality here: https://github.com/chocolatey/ChocolateyGUI/pull/823 would be great if you can provide feedback on that.  I am going to close this issue out as a duplicate.

**Closed by gep13** 2021-04-09 19:25 UTC
Labels: Duplicate
