### ISSUE TITLE
Unhandled Exception when viewing (package) choco-protocol-support

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#649] opened 2019-02-19 22:06 UTC
![image](https://user-images.githubusercontent.com/14026600/53050860-276c9900-344f-11e9-80d2-f08a95202cff.png)

![image](https://user-images.githubusercontent.com/14026600/53050956-74506f80-344f-11e9-969d-260fc8c54cb0.png)

**Comment by gep13** [comment] 2019-04-19 09:19
@bcurran3 can you confirm if this is still an issue?  I have just tested this with the latest pre-release version of Chocolatey GUI, and I am unable to reproduce.

For now, I am going to close this out, but feel free to re-open if you believe there is still a problem

**Closed by gep13** 2019-04-19 09:19 UTC
Labels: Can't Reproduce

**Comment by bcurran3** [comment] 2019-04-19 15:57
It's an issue with the last release, I don't know about the pre-release. You'll have to point me in the direction of the pre-release if you'd like me to try it.

**Comment by gep13** [comment] 2019-04-19 19:54
@bcurran3 the instructions for installing the pre-release version is documented here:

https://github.com/chocolatey/ChocolateyGUI#installation

**Comment by bcurran3** [comment] 2019-04-20 01:14
Something's not right.

![image](https://user-images.githubusercontent.com/14026600/56449507-d3efbd80-62ce-11e9-8025-69a2f12196d1.png)

![image](https://user-images.githubusercontent.com/14026600/56449511-deaa5280-62ce-11e9-801a-e1a10c62c94a.png)

**Comment by AdmiringWorm** [comment] 2019-04-20 01:21
@bcurran3 since you already have a version installed, you'll need to do a `choco upgrade` instead of `choco install`

**Comment by bcurran3** [comment] 2019-04-20 05:37
Cool. That wasn't in the instructions. :)

![image](https://user-images.githubusercontent.com/14026600/56453183-4d010c00-62f3-11e9-8f8c-ce3e31975435.png)

![image](https://user-images.githubusercontent.com/14026600/56453194-80439b00-62f3-11e9-8b9a-19d1f3265d5a.png)

Appears to be fixed.

![image](https://user-images.githubusercontent.com/14026600/56453200-b4b75700-62f3-11e9-9087-1a6165c04fa2.png)
