### ISSUE TITLE
Pulling outdated information should not block and should not show up in logs

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#616] opened 2018-08-22 14:48 UTC
@gep13 we discussed this and you may have already created an issue - feel free to close this as a duplicate if you have. Otherwise feel free to fill this out a bit better

**Comment by gep13** [comment] 2019-04-23 08:16
@ferventcoder this is a duplicate of this one: https://github.com/chocolatey/ChocolateyGUI/issues/525

**Closed by gep13** 2019-04-23 08:16 UTC
Labels: Duplicate
