### ISSUE TITLE
Can't install any programs "unable to read package from path"

### ISSUE THREAD

**Issue by KarStudio** [chocolatey/ChocolateyGUI#600] opened 2018-06-18 05:17 UTC
Unable to read package from path 'ChocolateyGUI\ChocolateyGUI.nupkg'.

How to solve it?

**Comment by gep13** [comment] 2018-06-18 10:28
@KarStudio can you provide more information about exactly the problem that you are facing?

What are you doing when you see that error?

Can you provide a complete set of steps to reproduce this problem?

**Comment by ruwanthaka** [comment] 2018-07-03 08:47
We are facing the same problem , but the problem is same nuget is working fine on anther machine , but the server ( Windows server 2012R2) fails without any valid reason . 
Same time different nuget packages are installed without this issue 
Complete error message is 
Parsing -version resulted in error (converted to warning):
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.11
Installing the following packages:
‘<package name>’
By installing you accept licenses for the packages.
Unable to read package from path ‘<package name>\<package name>.nupkg'.

**Comment by jakobht** [comment] 2018-11-10 19:49
I got the same error. I first ran out of disk space while installing git `choco install git`. I then cleared some space and reran `choco install git` and got the error:
```
PS C:\WINDOWS\system32> choco install git  -fv
Chocolatey v0.10.11
Installing the following packages:
git
By installing you accept licenses for the packages.
Unable to read package from path 'git.install\git.install.nupkg'.
``

I then solved the problem by deleting the git.install folder in C:\ProgramData\chocolatey\lib.

**Comment by cniweb** [comment] 2019-04-10 22:43
I have the same error:
```
C:\WINDOWS\system32>choco install git -fv
Chocolatey v0.10.13
Installing the following packages:
git
By installing you accept licenses for the packages.

Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Unable to read package from path 'git.install\git.install.nupkg'
```

**Comment by gep13** [comment] 2019-04-11 07:00
@cniweb are you able to try the workaround suggested by @jakobht ?

**Comment by gep13** [comment] 2019-04-11 07:01
Since this is not an issue with Chocolatey GUI, I am going to go ahead and close this issue.

**Closed by gep13** 2019-04-11 07:01 UTC

**Comment by cniweb** [comment] 2019-04-12 19:44
@gep13 Yes it helps me.

**Comment by 3rd3** [comment] 2022-01-01 17:00
I ran into a similar issue when I changed the hostname of the PC. Reboot solved it for me.
